sudo: false

language: python

python:
    - "3.2"
    - "3.3"
    - "3.4"

install:
    - python setup.py --quiet install

script:
    - python test.py
    - ./run_doctest.py -v README.rst download_lt.py
    - ./test.bash

    # Smoke test.
    - echo 'This is a sentence.' > foo.txt
    - language-check foo.txt
    - language-check --version
