language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip --quiet install 3to2; fi
    - python setup.py --quiet install

script:
    - python test.py
    - ./test.bash
